In [1]:
import numpy as np

In [5]:
numbers = [1,3,4,5,6,6,7]
arr1 = np.array(numbers)
arr1

array([1, 3, 4, 5, 6, 6, 7])

In [11]:
## a nested array
numbers2 = [[1,1,2],[2,4,5]]
arr2 = np.array(numbers2)
print(arr2)
print(arr2.ndim) # TO GET THE NUMBER OF DIMENSIONS FOR THE ARRAY
print(arr2.dtype) # to get the data type of the array 

[[1 1 2]
 [2 4 5]]
2
int32


In [19]:
# creating arrays with similar data types
arr3= np.ones([5])
arr4 = np.zeros(6)
print(arr4, arr3)

[0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]


In [20]:
# creating arrays with specif datatypes
arr5= np.array([1,2,3,4,5],dtype=np.float)
arr5 

array([1., 2., 3., 4., 5.])

In [21]:
# we can convert the existing array to a different data type.
array6 = arr5.astype(np.int64)
array6

array([1, 2, 3, 4, 5], dtype=int64)

In [35]:
list0 = np.array([[6,7,7],[8,0,1]])
list1 =np.array( [[8,7,6],[9,3,4]])
print(list1)
print(list0)

[[8 7 6]
 [9 3 4]]
[[6 7 7]
 [8 0 1]]


In [38]:
list01 =list0+list1 # performing arithmetic 
#operations on arrays
list01

array([[14, 14, 13],
       [17,  3,  5]])