In [1]:
import numpy as np

In [2]:
numbers = [1,3,4,5,6,6,7]
arr1 = np.array(numbers)
arr1

array([1, 3, 4, 5, 6, 6, 7])

In [3]:
## a nested array
numbers2 = [[1,1,2],[2,4,5]]
arr2 = np.array(numbers2)
print(arr2)
print(arr2.ndim) # TO GET THE NUMBER OF DIMENSIONS FOR THE ARRAY
print(arr2.dtype) # to get the data type of the array 

[[1 1 2]
 [2 4 5]]
2
int32


In [4]:
# creating arrays with similar data types
arr3= np.ones([5])
arr4 = np.zeros(6)
print(arr4, arr3)

[0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]


In [5]:
# creating arrays with specif datatypes
arr5= np.array([1,2,3,4,5],dtype=np.float)
arr5 

array([1., 2., 3., 4., 5.])

In [6]:
# we can convert the existing array to a different data type.
array6 = arr5.astype(np.int64)
array6

array([1, 2, 3, 4, 5], dtype=int64)

In [7]:
list0 = np.array([[6,7,7],[8,0,1]])
list1 =np.array( [[8,7,6],[9,3,4]])
print(list1)
print(list0)

[[8 7 6]
 [9 3 4]]
[[6 7 7]
 [8 0 1]]


In [8]:
list01 =list0+list1 # performing arithmetic 
#operations on arrays
list01

array([[14, 14, 13],
       [17,  3,  5]])

In [9]:
## accessing different indexes
array6[0]

1

In [10]:
# slicing the array.
array6[1:2]

array([2], dtype=int64)

In [11]:
array6[2:3] # from the second value.

array([3], dtype=int64)

In [12]:
#Slicing and indexing a two dimensional array.
list01


array([[14, 14, 13],
       [17,  3,  5]])

In [13]:
list01[1,2]

5

In [14]:
#  slicing  a multidimension array
list_11= np.array([[23,44,44,45,7],[8,9,7,8,6],[65,87,43,21,4]])
list_11

array([[23, 44, 44, 45,  7],
       [ 8,  9,  7,  8,  6],
       [65, 87, 43, 21,  4]])

In [15]:
list_0=list_11[:1,:2]
list_0

array([[23, 44]])

In [16]:
list_1=list_11[:1,:3] # to get the top raw of the matrix.
list_1

array([[23, 44, 44]])

In [17]:
list_2 = list_11[3:4,:4]
list_2

array([], shape=(0, 4), dtype=int32)